### PR TITLE
Patch 10_Ethics_and_Responsible_Disclosure

### PR DESCRIPTION
**Pull request by tamir20**
added grammarly and some other cosmetics changes.
by the way, the book does compile, but the bibliographic part wont be displayed in the original branch, thus all the references are broken. maybe its just a matter of wrong compiling software in my computer.
edited by Tamir Khoramian (תמיר חורם-יאן) 312278070

### CODE REVIEW

**Comment by royhershkovitz** [comment]
please put the pr in the new repo

**Comment by royhershkovitz** [comment]
it should appear here
https://github.com/Yossioren/AttacksonImplementationsCourseBook/pulls

**Comment by tamir20** [comment]
עשיתי את ההעתק במקום הנכון.
קוראים לזה grammar fixing for chapter 10

עוד לא מחקתי את הישן

בתאריך יום ב׳, 8 ביוני 2020, 11:57, מאת roy hersh ‏<notifications@github.com

**Comment by royhershkovitz** [comment]
thank you I just want to make sure

**Pull request closed without merging**
